### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ClemFR** [Sp00p64/DiscordRAT#1]
When I try to run your file "DiscordRAT(withCV).py", I have a windows thet appears with title "SyntaxError" and it says "inconsistent use of tabs and spaces in indentation"

**Comment by Sp00p64** [comment]
Hi, this is a common problem in python3, but is very easy to solve.
Simply open the python file in you chosen IDE and convert all indentation to tabs,so if you use sublime text for exemple you need to click on the "Tab size" button on the bottom right and then click on  "Convert identation to tabs".
Hope this helps.
