### ISSUE TITLE
issues with bot

### ISSUE THREAD

**Issue by j-555** [Sp00p64/DiscordRAT#11]
so the bot tells me the session has started, but when i try to do ‘!interact uuid’ nothing happens, no help message, no system info, just wondering if you knew how to fix this

**Comment by Sp00p64** [comment]
Hi, you need to type "!interact [INSERT UUID GIVEN BY BOT] " not the word "uuid"
Hope I'm clear, good luck

**Comment by j-555** [comment]
sorry for not making it clear, that is what i’m doing but it doesn’t work anyway, the bot doesn’t return and messages and the functions don’t work
