### ISSUE TITLE
Can't interact (Using NoCV) WithCV Doesn't work and NoCV Seems to have an error

### ISSUE THREAD

**Issue by BYZINTAY** [Sp00p64/DiscordRAT#14]
WithCV Instantly closes and NoCV After having it open does this, 
![image](https://user-images.githubusercontent.com/70487971/94618711-917b3000-0279-11eb-8816-c009d7ede913.png)
I does post the information but I can't interact with it
![image](https://user-images.githubusercontent.com/70487971/94618861-dd2dd980-0279-11eb-9264-eb7780706354.png)
 I'm not sure if i'm doing this wrong or if i'm just dumb im a bit new to this sorry! I posted the right channel ID and token and thats all I editted with the code I have the most recent version of py I think and when I install requirements it says it can't find tkinker or something like that, my discord is VI#6000 if you would like to talk! Seems cool though

**Comment by RainCloud1337** [comment]
Same :((

**Comment by priyamsahoo** [comment]
This issue has been resolved. You can check out my repository for the same, unless my code is merged.
(I have opened a PR)

**Comment by Sp00p64** [comment]
It took me a while to get back on this project but @priyamsahoo code has now been merged into master which should fix this problem.
