### ISSUE TITLE
How to use DiscordRAT

### ISSUE THREAD

**Issue by TBMgames** [Sp00p64/DiscordRAT#17]
**I have successfully managed to receive a UUID in my discord chat. When I perform this command "!interact [ff636ff6-618a-4ad4-a256-626cc2c9db86]" (I've also tried without the square brackets) it returns nothing. If possible could we have clear instructions on how to operate the bot maybe a video or clear image? 

Thanks :)** 

![Capture](https://user-images.githubusercontent.com/44858269/98239697-144b8500-1fb4-11eb-9384-d7864d0909ad.PNG)

**Comment by priyamsahoo** [comment]
You have to pass in the UUID as a parameter in "!interact" command

**Comment by Shromm-Gaind** [comment]
@priyamsahoo Could you show an example?

**Comment by priyamsahoo** [comment]
> **I have successfully managed to receive a UUID in my discord chat. When I perform this command "!interact [ff636ff6-618a-4ad4-a256-626cc2c9db86]" (I've also tried without the square brackets) it returns nothing. If possible could we have clear instructions on how to operate the bot maybe a video or clear image?
> 
> Thanks :)**
> 
> ![Capture](https://user-images.githubusercontent.com/44858269/98239697-144b8500-1fb4-11eb-9384-d7864d0909ad.PNG)

After using the !interact command (without the brackets), it wont return anything, but the session will start. You can try running !sysinfo after the !interact command. It will give you output.
