### ISSUE TITLE
Syntaxe Error

### ISSUE THREAD

**Issue by gaz0** [Sp00p64/DiscordRAT#19]
when i type the comand for build the files in .exe he tell me this error message.

![error](https://user-images.githubusercontent.com/71967147/102509122-748b1780-4086-11eb-91f5-8165fe854c77.PNG)

**Comment by Sp00p64** [comment]
This is an issue with bash since the program name contains parentheses try putting the program name in quotation marks :
Pyinstaller --onefile --noconsole "DiscordRat(WithCV).py" if that doesn't solve it rename the program so that it doesn't contain parentheses anymore.
