### ISSUE TITLE
Hi Bro can you help me please thanks

### ISSUE THREAD

**Issue by devil67** [Sp00p64/DiscordRAT#2]
python3 DiscordRAT.py
Traceback (most recent call last):
  File "DiscordRAT.py", line 2, in <module>
    import winreg
ModuleNotFoundError: No module named 'winreg'

**Comment by Sp00p64** [comment]
Something seems to be off with your python install since winreg is a built-in module of python3.
You can install another version of python3,or create  a python3 virtual environment , and execute the script from there.
Hope this helps.

**Comment by donutz10** [comment]
> python3 DiscordRAT.py
> Traceback (most recent call last):
> File "DiscordRAT.py", line 2, in
> import winreg
> ModuleNotFoundError: No module named 'winreg'

pip3 install winreg, and restart
