### ISSUE TITLE
on_ready error.

### ISSUE THREAD

**Issue by zu0a** [Sp00p64/DiscordRAT#20]
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\zu0a.DESKTOP-4C64LHH\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "DiscordRAT(NoCV).py", line 124, in on_ready
    await client.guilds[0].system_channel.send(value2)
AttributeError: 'NoneType' object has no attribute 'send'
```  
Not quite sure what's causing this, I tried this with CV and without CV, same error regardless.

**Comment by zu0a** [comment]
Nevermind, I have severe brain damage.

**Comment by zu0a** [comment]
Maybe I'm not retarded, I thought the error was because I didn't have the bot in the server I was trying to use, but it's still throwing the error.

**Comment by zu0a** [comment]
Figured it out, the messages are sent to the servers channel for welcome messages and boosts, not sure why.

**Comment by appelsiensam** [comment]
So what is the problem? I have the exact same issue.
