### ISSUE TITLE
What’s the difference with / without CV?

### ISSUE THREAD

**Issue by AstroOrbis** [Sp00p64/DiscordRAT#21]

**Comment by Sp00p64** [comment]
As explained in the README , WithCV has webcam related modules by importing the opencv library the other does not , I decided to do 2 different files because the opencv library adds ~40-50 MB to the compiled exe.

**Comment by AstroOrbis** [comment]
but is there any difference?

**Comment by AstroOrbis** [comment]
like if one is faster or something

**Comment by bboychris168** [comment]
@AstroOrbis he literally just said it adds 40 to 50 mbs more to the compiled version, hence why there is a CV and without CV.
