### ISSUE TITLE
Like the idea, lots of bugs

### ISSUE THREAD

**Issue by Hellinduction** [Sp00p64/DiscordRAT#24]
So I really like the idea of this rat and playing around with it has been somewhat fun. The problem I have is alot of the features don’t seem to be working correctly or at all.

Next time I get on my PC I will test each feature and give a list of working features and a list of none working features.

**Comment by Sp00p64** [comment]
Yeah,I've barely maintained it and it's my second coding project ever so the code's quite terrible,I'll try to make it work again when I get the time.

**Comment by bboychris168** [comment]
Ok thanks! So this project is currently unmantained?

**Comment by Sp00p64** [comment]
Currently yes

**Comment by Sp00p64** [comment]
Project is maintained again,I just release a big update, feel free to tell me if you still encounter issues now.
(Make sure to read README as the way the program works has changed.)
