### ISSUE TITLE
COMMANDS DONT WORK

### ISSUE THREAD

**Issue by NBDMatr1x** [Sp00p64/DiscordRAT#25]
so the commands don't work I get a new connection I do some commands and nothing shows and works up this is either a bug or something in the code or this is maybe something on my side I haven't been able to install the requirements because of tkinter I just get a lot of errors from it could be also that

**Comment by Sp00p64** [comment]
As seen in error #24 the projet is currently bugged and unmaintained , I'll fix it when I get around to it.

**Comment by NBDMatr1x** [comment]
ok it was actually my side but there are some commands that dont work but overall its very good hopefully u can mantain and update it as soon as possible

**Comment by Sp00p64** [comment]
I posted a big update to the program,feel free to open a new issue if you encounter problems.
(Make sure to read README as the way the program works has changed.)

**Comment by NBDMatr1x** [comment]
ok thank you i will test it out on a vm
