### ISSUE TITLE
.exe issues 

### ISSUE THREAD

**Issue by Epik123** [Sp00p64/DiscordRAT#36]
So I compiled it correctly into a .exe and it wont stay open long enough to make the bot make a channel to control the pc even with my av off

**Comment by Sp00p64** [comment]
Does the program work uncompiled ?

**Comment by Epik123** [comment]
> Does the program work uncompiled ?

Yes it works perfectly fine but as soon as it get compiled it no longer works

**Comment by Sp00p64** [comment]
Did you try compiling the program without the `--noconsole` option ?

**Comment by Sp00p64** [comment]
Closing this for now due to lack of response.
