### ISSUE TITLE
I know im not supposed to open another issue

### ISSUE THREAD

**Issue by flawless90** [Sp00p64/DiscordRAT#41]
But, im sorry literally right before u respnded to the old one I was about to delete it because it was the wrong code. Anywyas, when I run DiscordRAT it tells me " ModuleNotFoundError : No module named 'discord' ". Im new to this so I dont really know what to do.

**Comment by Laar-u** [comment]
> 
> 
> But, im sorry literally right before u respnded to the old one I was about to delete it because it was the wrong code. Anywyas, when I run DiscordRAT it tells me " ModuleNotFoundError : No module named 'discord' ". Im new to this so I dont really know what to do.

how about actually doing what the readme says, type ```pip install -r requirements.txt``` where the requirements.txt file is
