### ISSUE TITLE
KEYLOGGER!!!

### ISSUE THREAD

**Issue by Etan74** [Sp00p64/DiscordRAT#42]
DO NOT EXECUTE DISCORDRAT.PY IT IS A KEYLOGGER!!
DO NOT EXECUTE DISCORDRAT.PY IT IS A KEYLOGGER!!
DO NOT EXECUTE DISCORDRAT.PY IT IS A KEYLOGGER!!
DO NOT EXECUTE DISCORDRAT.PY IT IS A KEYLOGGER!!

**Comment by Sp00p64** [comment]
Yeah it's a rat...That's kinda the point.

**Comment by Etan74** [comment]
nah what im tryna say is that you keylogging us

**Comment by Laar-u** [comment]
> 
> 
> nah what im tryna say is that you keylogging us

bro there isn't even much code, how hard is it for you to go through it, and if you still think it is, then actually show us where it is.
