### ISSUE TITLE
Actual question.

### ISSUE THREAD

**Issue by Magical2x5** [Sp00p64/DiscordRAT#45]
Hello there, i'm new to using rats. first of all i wanted to thank you for making this as this is great for research on malware, trojans and stuff. 

let's say i were to send this to someone to infect their computer. im testing this on my own computer, what files contains the backdoor that will open the session, because im provided with DiscordRAT.py. do i just hide that file in another and send it or manually insert it onto another computer? 

or does the infected computer have to run the python file?

**Comment by Sp00p64** [comment]
As the README says you can either run the file with python or compile the file to an exe using PyInstaller and then distribute the exe.
