### ISSUE TITLE
how do i run it

### ISSUE THREAD

**Issue by 51Corpz** [Sp00p64/DiscordRAT#48]
i put python discordRAT.py and it just said invalid syntax (im new to this stuff)
i already put the bot token in

now what

**Comment by evoreign** [comment]
turn it into exe and send it to your victim, if the victim runs it then you would gain access

**Comment by slitmyeyes** [comment]
What exactly do you turn into the exe, super new and dont really understand the turning into exe part

**Comment by D0RL** [comment]
@evoreign could I get your discord to ask you about this topic

**Comment by Sp00p64** [comment]
Read README.
