### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by Debeselis420** [Sp00p64/DiscordRAT#5]
Hi, after 3hours of python mess i came to and end with these errors:
https://imgur.com/a/m98I2EU
Also CV doesn't open, just this one
all the bot says is 
https://imgur.com/a/3wN5lqa
Any help appreciated

**Comment by Sp00p64** [comment]
The "chosen" is not defined is normal, program should be working fine even though the error is showing, and as stated in the readme.md once the bot says "session opened" you need to type "!interact random uuid" with the random uuid being the number shown after "session opened"

**Comment by Debeselis420** [comment]
Ty for fast response, after writing !interact random uuid nothing happens, could it be because of my discord bot code ?

**Comment by Sp00p64** [comment]
If the "random uuid" is the right number given by the bot then it should work try typing "!help" to check if bot if working correctly

**Comment by Debeselis420** [comment]
All I get is this
 https://imgur.com/a/gJXw5Ls

**Comment by Debeselis420** [comment]
ive just seen, the interact and I wrote opened, I was in a hurry and this is just an exampe

**Comment by Sp00p64** [comment]
You should not write "!interact opened random uuid" just "!interact random uuid" then check if bot works with "!help" if this still does not work,try running the script in a python3 virtual environmment

**Comment by Debeselis420** [comment]
"!interact opened random uuid" I wrote like this by accident as an example, I will try virtual env right now and get back to you

**Comment by Debeselis420** [comment]
Same errors that I sent, but now they both come on every time I turn the script on or everytime type !help / !interact, then after some typing it doesnt react

**Comment by Sp00p64** [comment]
Does the "!sysinfo" command work ?

**Comment by Sp00p64** [comment]
Also when using the "!interact" command be careful to not select spaces before the uuid
Exemple : "!interact 84389839" works but "!interact  84389839" does not

**Comment by Debeselis420** [comment]
https://imgur.com/a/4GsfhcY
Sadly no, when using !sysinfo i get this error again, and everytime i type a command it's always these 2 over and over untill it just does nothing

**Comment by Sp00p64** [comment]
Very strange..What I recommand for now is to delete the lines 114 to 120(NoCV) until I find what's going on

**Comment by Sp00p64** [comment]
After deleting those lines do not use "!interact" or copy the uuid, you can just directly use "!help" or other commands

**Comment by Debeselis420** [comment]
Okay it works now, thank you, and how does one infect a computer with this rat ?

**Comment by Sp00p64** [comment]
A computer can only be infected by this rat if you execute the compiled binary of the python script on it.Do not use this program to infect a computer that you do not own.
