### ISSUE TITLE
AM I DUMB?

### ISSUE THREAD

**Issue by Orert** [Sp00p64/DiscordRAT#52]
i downloaded the needed things and it won't work, when running it i get "Traceback (most recent call last):
  File "C:/Users/Orert/DiscordRAT.py", line 9, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'"

**Comment by dk3775** [comment]
Which command did you run first?, I mean just after downloading.

**Comment by Sp00p64** [comment]
Read README.
