### ISSUE TITLE
Identation Error 

### ISSUE THREAD

**Issue by die-dimitry** [Sp00p64/DiscordRAT#6]
https://ibb.co/S50Vc80   This is the error i am unable to fix. Happens same for with cv and w/o CV

While installing requirements using pip3 **tkinter** has been removed so couldnt install it rest
i was able to install all of them.
Also
First i was getting some identation error because of some 'tabs' used instead of space but i converted them into 'space' using VS2019. 
Can you check once agaiin with your latest commit,
do u have any video when u ran the programme ?

**Comment by Sp00p64** [comment]
If you struggle with indentation errors you can use autopep8.
`pip install autopep8`
`autopep8 -i DiscordRAT.py `
