### ISSUE TITLE
Not an issue, just some questions.

### ISSUE THREAD

**Issue by donutz10** [Sp00p64/DiscordRAT#7]
Hey,
I wonder, do the victims have to download something or do they have to be in the same server I am in?
Can I get their discord creds? I'm guessing yes?
What is the most use of this tool that is funny?
Thanks.

**Comment by Zirzux** [comment]
Ikr, i dont fucking understand what they mean by "DiscordRat" lmao, just the same question as yours , "do they need to download some shit?".

**Comment by Sp00p64** [comment]
Beforehand I must warn you that the execution of this program on any machine that you do not own is illegal,the """victims""" have to download the compiled script and do not need to be on the same server has you and no this RAT does not steal discord creds.
